/**
 * The Zesst Now mark, inlined so it stays crisp at any size and needs no
 * network request. Geometry is generated by brand/brandgen.py — edit it there
 * and re-run, don't hand-tweak the path here or the SVG exports drift out of
 * sync with the site.
 */

const Z_PATH = "M33.50,20 H70 V30 L43,66 H70 L62.50,76 H26 V66 L53,30 H26 Z";

export default function Mark({
  size = 30,
  /** Drops the tile and draws the Z in the current text colour. */
  bare = false,
  className,
}: {
  size?: number;
  bare?: boolean;
  className?: string;
}) {
  // Gradient ids must be unique per instance or the first one on the page wins.
  const id = `zg-${bare ? "bare" : "tile"}-${size}`;

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 96 96"
      className={className}
      role="img"
      aria-label="Zesst Now"
      style={{ display: "block", flex: "none" }}
    >
      {bare ? (
        <path d={Z_PATH} fill="currentColor" />
      ) : (
        <>
          <defs>
            <linearGradient id={id} x1="0" y1="0" x2="1" y2="1">
              <stop offset="0" stopColor="#E8D9A8" />
              <stop offset="1" stopColor="#C9A961" />
            </linearGradient>
          </defs>
          <rect width="96" height="96" rx="22" fill={`url(#${id})`} />
          <path d={Z_PATH} fill="#05060F" />
        </>
      )}
    </svg>
  );
}
