# -*- coding: utf-8 -*-
"""Six Reels, rewritten for pace.

Roughly twice as many beats as v1, each about half as long. A spoken line here
is one clause, not one paragraph — which is what lets the cut land every two to
three seconds instead of every six.

Every scene names a visual, and the visual is specific to the service: a
browser for websites, a home screen for apps, a dashboard for SaaS, a wire for
automation, a funnel for the funnel, a calendar for scheduling. That is the
second half of the fix — six services that looked identical now do not.
"""

REELS = [

# ══════════════════════════════════════════════════════════════════════
dict(id="mon-website", day="Monday", service="Website design",
     desk="GST & tax compliance", theme="website", scenes=[

  dict(kind="kinetic", vo="आपकी वेबसाइट है।",
       big='आपकी वेबसाइट <span class=hl>है।</span>'),
  dict(kind="kinetic", vo="कॉल एक भी नहीं आती।",
       big='कॉल <span class=hl>एक भी नहीं।</span>'),
  dict(kind="browser", vo="देखने में तो ठीक लगती है।",
       big="देखने में ठीक है", url="yourbusiness.in", blocks=5),
  dict(kind="kinetic", vo="पर ये दुकान नहीं है। ब्रोशर है।",
       big='ये दुकान नहीं।<br><span class=hl>ब्रोशर है।</span>', size="md"),
  dict(kind="kinetic", vo="ब्रोशर से कोई खरीदता नहीं।",
       big='ब्रोशर से कोई<br><span class=hl>खरीदता नहीं।</span>', size="md"),
  dict(kind="versus", vo="ज़्यादातर एजेंसी डिज़ाइन बेचती है। हम एन्क्वायरी।",
       a_label="वो बेचते हैं", a="डिज़ाइन",
       b_label="हम बेचते हैं", b="एन्क्वायरी"),
  dict(kind="kinetic", vo="अब असली बात।",
       big='अब <span class=hl>असली बात।</span>'),
  dict(kind="form", vo="ये फ़ॉर्म मैं अभी भर रहा हूँ।",
       big="अभी भर रहा हूँ", title="एन्क्वायरी", btn="भेजिए",
       rows=[("नाम", "सुनील"), ("फ़ोन", "98••• •••21"), ("क्या चाहिए", "वेबसाइट")]),
  dict(kind="notif", vo="और ये देखिए। फ़ोन पर आ गया।",
       big="फ़ोन पर आ गया", title="नई एन्क्वायरी",
       body="सुनील · वेबसाइट", time="अभी"),
  dict(kind="kinetic", vo="इसी वक़्त। कोई देरी नहीं।",
       big='इसी वक़्त।<br><span class=hl>कोई देरी नहीं।</span>', size="md"),
  dict(kind="kinetic", vo="ज़्यादातर वेबसाइट में यही नहीं होता।",
       big='ज़्यादातर में<br>यही नहीं होता।', size="md"),
  dict(kind="counter", vo="अड़तालीस घंटे।", to="48", unit="घंटे",
       ramp=["09", "17", "24", "31", "38", "44"],
       sub="शुरू से लाइव तक"),
  dict(kind="kinetic", vo="ये अंदाज़ा नहीं है। तय है।",
       big='अंदाज़ा नहीं।<br><span class=hl>तय है।</span>', size="md"),
  dict(kind="ticks", vo="होस्टिंग। कंटेंट एडिटर। एन्क्वायरी डेस्क।",
       big="सब इसी में", items=["होस्टिंग", "कंटेंट एडिटर", "एन्क्वायरी डेस्क"]),
  dict(kind="kinetic", vo="अलग से कोई बिल नहीं।",
       big='अलग से<br><span class=hl>कोई बिल नहीं।</span>', size="md"),
  dict(kind="end", vo="वेबसाइट चाहिए? लिंक बायो में।",
       big='वेबसाइट <span class=hl>चाहिए?</span>'),
]),

# ══════════════════════════════════════════════════════════════════════
dict(id="tue-app", day="Tuesday", service="App development",
     desk="Loan facilitation", theme="app", scenes=[

  dict(kind="kinetic", vo="ऐप बनवाने से पहले।",
       big='ऐप बनवाने <span class=hl>से पहले।</span>', size="md"),
  dict(kind="kinetic", vo="ये एक सवाल पूछ लीजिए।",
       big='ये <span class=hl>एक सवाल।</span>'),
  dict(kind="label", vo="क्या इसे प्ले स्टोर पर होना ज़रूरी है?",
       eyebrow="सवाल", big='प्ले स्टोर पर<br>ज़रूरी है?'),
  dict(kind="kinetic", vo="या बस ग्राहक के फ़ोन पर खुल जाए?",
       big='या बस फ़ोन पर<br><span class=hl>खुल जाए?</span>', size="md"),
  dict(kind="kinetic", vo="ज़्यादातर के लिए जवाब दूसरा है।",
       big='ज़्यादातर के लिए<br><span class=hl>दूसरा।</span>', size="md"),
  dict(kind="home", vo="देखिए। चार टैप।",
       big="चार टैप", slot=5, label="आपका ऐप — होम स्क्रीन पर"),
  dict(kind="kinetic", vo="स्टोर नहीं। रिव्यू नहीं। इंतज़ार नहीं।",
       big='स्टोर नहीं।<br>रिव्यू नहीं।<br><span class=hl>इंतज़ार नहीं।</span>', size="md"),
  dict(kind="ticks", vo="इंस्टॉल होता है। ऑफ़लाइन चलता है। नोटिफ़िकेशन भेजता है।",
       big="और ये सब करता है",
       items=["इंस्टॉल होता है", "ऑफ़लाइन चलता है", "नोटिफ़िकेशन भेजता है"]),
  dict(kind="versus", vo="स्टोर का रिव्यू दो हफ़्ते। ये उसी दिन।",
       a_label="प्ले स्टोर", a="दो हफ़्ते",
       b_label="ये तरीक़ा", b="उसी दिन"),
  dict(kind="counter", vo="और लागत? लगभग तीन गुना कम।", to="3×", unit="कम",
       ramp=["1.1", "1.6", "2.0", "2.4", "2.8"],
       sub="स्टोर वाले ऐप के मुक़ाबले"),
  dict(kind="kinetic", vo="पर एक बात साफ़ कर दूँ।",
       big='एक बात <span class=hl>साफ़।</span>'),
  dict(kind="kinetic", vo="कभी कभी स्टोर वाला ही सही होता है।",
       big='कभी कभी स्टोर वाला<br><span class=hl>ही सही है।</span>', size="md"),
  dict(kind="ticks", vo="कैमरा गहराई से चाहिए। बैकग्राउंड लोकेशन चाहिए। पेमेंट एसडीके चाहिए।",
       big="जब ये चाहिए",
       items=["कैमरा, गहराई से", "बैकग्राउंड लोकेशन", "पेमेंट SDK"]),
  dict(kind="kinetic", vo="ऐसा हो तो हम यही कहेंगे।",
       big='ऐसा हो तो<br><span class=hl>हम यही कहेंगे।</span>', size="md"),
  dict(kind="end", vo="कौन सा चाहिए, पहली मीटिंग में तय।",
       big='पहली मीटिंग में <span class=hl>तय।</span>'),
]),

# ══════════════════════════════════════════════════════════════════════
dict(id="wed-saas", day="Wednesday", service="SaaS development",
     desk="Registration & insurance", theme="saas", scenes=[

  dict(kind="kinetic", vo="सॉफ़्टवेयर किराए पर मत लीजिए।",
       big='सॉफ़्टवेयर किराए पर<br><span class=hl>मत लीजिए।</span>', size="md"),
  dict(kind="kinetic", vo="हर महीने। हर यूज़र का।",
       big='हर महीने।<br>हर यूज़र का।', size="md"),
  dict(kind="kinetic", vo="ज़रा साल भर जोड़िए।",
       big='साल भर <span class=hl>जोड़िए।</span>'),
  dict(kind="counter", vo="दस लोग। साठ हज़ार साल का।", to="₹60,000", unit="",
       ramp=["₹6,000", "₹18,000", "₹31,000", "₹44,000", "₹53,000"],
       sub="दस यूज़र · हर साल · और बढ़ता ही जाता है"),
  dict(kind="kinetic", vo="पाँच साल में तीन लाख।",
       big='पाँच साल में<br><span class=hl>तीन लाख।</span>', size="md"),
  dict(kind="kinetic", vo="और आख़िर में आपके पास कुछ नहीं।",
       big='और आख़िर में<br><span class=hl>कुछ नहीं।</span>', size="md"),
  dict(kind="kinetic", vo="इससे भी बड़ी बात ये है।",
       big='इससे भी <span class=hl>बड़ी बात।</span>', size="md"),
  dict(kind="kinetic", vo="टूल छोड़ेंगे तो डेटा उन्हीं के पास रह जाएगा।",
       big='टूल छोड़ेंगे तो<br><span class=hl>डेटा उन्हीं के पास।</span>', size="md"),
  dict(kind="rows", vo="ये बिज़जीएसटी प्रो है। यहीं बना है।",
       big="यहीं बना है", title="GST इनवॉइस",
       rows=[("माल", "₹ 42,000"), ("GST 18%", "₹ 7,560"), ("कुल", "₹ 49,560")]),
  dict(kind="dash", vo="और असली बिज़नेस इस पर चल रहे हैं।",
       big="असली बिज़नेस, असली डेटा", title="इस महीने की बिक्री",
       bars=[("अप्रै", 45), ("मई", 62), ("जून", 58), ("जुल", 78), ("अग", 92)]),
  dict(kind="ticks", vo="अपना डेटा। अपने नियम। कोई सीट गिनती नहीं।",
       big="अपना प्रोडक्ट माने",
       items=["अपना डेटा", "अपने नियम", "सीट गिनती नहीं"]),
  dict(kind="kinetic", vo="पर एक शर्त है।",
       big='पर एक <span class=hl>शर्त है।</span>'),
  dict(kind="kinetic", vo="दस यूज़र से कम हैं तो मत बनवाइए।",
       big='दस से कम?<br><span class=hl>तो मत बनवाइए।</span>', size="md"),
  dict(kind="kinetic", vo="बना बनाया टूल तब सस्ता है। हम यही कहेंगे।",
       big='तब बना बनाया<br>टूल सस्ता है।', size="md"),
  dict(kind="end", vo="अपना प्रोडक्ट चाहिए? बात कीजिए।",
       big='अपना प्रोडक्ट <span class=hl>चाहिए?</span>'),
]),

# ══════════════════════════════════════════════════════════════════════
dict(id="thu-ai", day="Thursday", service="AI for business",
     desk="Leads & marketing", theme="ai", scenes=[

  dict(kind="chat", vo="ये जवाब किसी ने टाइप नहीं किया।",
       big="किसी ने टाइप नहीं किया", time="11:04 PM",
       msgs=[("them", "बकाया कितना है?"), ("typing", ""),
             ("us", "₹ 12,400 — 3 दिन से<br>लिंक भेज दिया है")]),
  dict(kind="kinetic", vo="रात के ग्यारह बजे थे।",
       big='रात <span class=hl>ग्यारह बजे।</span>', size="md"),
  dict(kind="kinetic", vo="अपने आप गया।",
       big='<span class=hl>अपने आप।</span>'),
  dict(kind="kinetic", vo="ए आई को लेकर सबसे बड़ी गलतफ़हमी यही है।",
       big='सबसे बड़ी<br><span class=hl>गलतफ़हमी।</span>', size="md"),
  dict(kind="kinetic", vo="लोग सोचते हैं वो कुछ बड़ा करेगा।",
       big='लोग सोचते हैं<br>कुछ बड़ा करेगा।', size="md"),
  dict(kind="kinetic", vo="असल में वो एक छोटा काम करता है।",
       big='असल में<br><span class=hl>एक छोटा काम।</span>', size="md"),
  dict(kind="wire", vo="एन्क्वायरी आई। जवाब गया। रिमाइंडर लगा।",
       big="और वो हर बार यही करता है",
       nodes=["एन्क्वायरी आई", "जवाब गया", "रिमाइंडर लगा"]),
  dict(kind="ticks", vo="पेमेंट रिमाइंडर। एन्क्वायरी का जवाब। अपॉइंटमेंट की पुष्टि।",
       big="तीन जगह, हर बिज़नेस में",
       items=["पेमेंट रिमाइंडर", "एन्क्वायरी का जवाब", "अपॉइंटमेंट की पुष्टि"]),
  dict(kind="kinetic", vo="तीनों रोज़ होते हैं।",
       big='तीनों <span class=hl>रोज़।</span>'),
  dict(kind="kinetic", vo="और तीनों में सोचना नहीं पड़ता।",
       big='और सोचना<br><span class=hl>नहीं पड़ता।</span>', size="md"),
  dict(kind="counter", vo="एक छोटी टीम के ये रोज़ दो घंटे खाते हैं।", to="2", unit="घंटे रोज़",
       ramp=["0.3", "0.7", "1.1", "1.5", "1.8"],
       sub="एक छोटी टीम में · सिर्फ़ दोहराव"),
  dict(kind="kinetic", vo="अब जहाँ सोचना पड़ता है।",
       big='अब जहाँ <span class=hl>सोचना है।</span>', size="md"),
  dict(kind="versus", vo="दाम, छूट, कौन सी फ़ाइल बैंक जाएगी। वहाँ आदमी चाहिए।",
       a_label="वहाँ", a="दाम · छूट · कौन सी फ़ाइल",
       b_label="चाहिए", b="आदमी, AI नहीं"),
  dict(kind="kinetic", vo="हम वो नहीं बेचते। और जो बेचे उससे बचिए।",
       big='हम वो नहीं बेचते।<br><span class=hl>जो बेचे, बचिए।</span>', size="md"),
  dict(kind="kinetic", vo="ए आई आदमी की जगह नहीं लेता।",
       big='आदमी की जगह<br>नहीं लेता।', size="md"),
  dict(kind="end", vo="दोहराव की जगह लेता है। आपके यहाँ क्या दोहराया जाता है?",
       big='<span class=hl>दोहराव की</span> जगह।'),
]),

# ══════════════════════════════════════════════════════════════════════
dict(id="fri-funnel", day="Friday", service="Development funnel",
     desk="BizGST Pro", theme="funnel", scenes=[

  dict(kind="kinetic", vo="लीड आती है।",
       big='लीड <span class=hl>आती है।</span>'),
  dict(kind="kinetic", vo="और मर जाती है।",
       big='और <span class=hl>मर जाती है।</span>'),
  dict(kind="funnel", vo="रास्ता चार क़दम का है।",
       big="रास्ता चार क़दम का",
       stages=[("एन्क्वायरी", "100"), ("जवाब", "62"),
               ("फ़ॉलो अप", "18"), ("सौदा", "7")]),
  dict(kind="kinetic", vo="टूटता कहाँ है? तीसरे क़दम पर।",
       big='टूटता कहाँ?<br><span class=hl>तीसरे क़दम पर।</span>', size="md"),
  dict(kind="kinetic", vo="फ़ॉलो अप किसी ने किया ही नहीं।",
       big='फ़ॉलो अप<br><span class=hl>हुआ ही नहीं।</span>', size="md"),
  dict(kind="kinetic", vo="आलस की वजह से नहीं।",
       big='आलस की वजह<br>से नहीं।', size="md"),
  dict(kind="kinetic", vo="किसी की ज़िम्मेदारी ही नहीं थी।",
       big='ज़िम्मेदारी<br><span class=hl>किसी की नहीं थी।</span>', size="md"),
  dict(kind="kinetic", vo="और एक बात इससे भी बड़ी।",
       big='एक बात <span class=hl>इससे भी बड़ी।</span>', size="md"),
  dict(kind="versus", vo="पहला जवाब दस मिनट में या दस घंटे में?",
       a_label="दस घंटे में", a="ठंडी लीड",
       b_label="दस मिनट में", b="बात बन जाती है"),
  dict(kind="kinetic", vo="अब एक ग़लतफ़हमी दूर कर दूँ।",
       big='एक <span class=hl>ग़लतफ़हमी।</span>'),
  dict(kind="kinetic", vo="फ़नल कोई सॉफ़्टवेयर नहीं है।",
       big='फ़नल कोई<br><span class=hl>सॉफ़्टवेयर नहीं।</span>', size="md"),
  dict(kind="kinetic", vo="सी आर एम ख़रीदने से फ़ॉलो अप नहीं होता।",
       big='CRM से फ़ॉलो अप<br>नहीं होता।', size="md"),
  dict(kind="ticks", vo="तुरंत जवाब। तीसरे दिन याद। सातवें दिन आख़िरी बार।",
       big="फ़नल का मतलब है",
       items=["तुरंत जवाब", "तीसरे दिन याद", "सातवें दिन आख़िरी"]),
  dict(kind="counter", vo="एक असली केस। इकतालीस प्रतिशत ज़्यादा सौदे।",
       to="+41%", unit="", ramp=["+6%", "+14%", "+22%", "+30%", "+36%"],
       sub="वही लीड · वही टीम · सिर्फ़ फ़ॉलो अप अपने आप"),
  dict(kind="end", vo="आपकी लीड कहाँ रुक रही है? हम बता देंगे।",
       big='आपकी लीड <span class=hl>कहाँ रुकी?</span>'),
]),

# ══════════════════════════════════════════════════════════════════════
dict(id="sat-social", day="Saturday", service="Social media automation",
     desk="Cognitive Capital Suite", theme="social", scenes=[

  dict(kind="kinetic", vo="ये पोस्ट मैंने आज नहीं डाली।",
       big='ये पोस्ट आज<br><span class=hl>नहीं डाली।</span>', size="md"),
  dict(kind="kinetic", vo="तीन हफ़्ते पहले डाली थी।",
       big='तीन हफ़्ते <span class=hl>पहले।</span>', size="md"),
  dict(kind="kinetic", vo="और जा अभी रही है।",
       big='जा <span class=hl>अभी रही है।</span>'),
  dict(kind="cal", vo="पूरा महीना कतार में लगा हुआ है।",
       big="पूरा महीना, कतार में", title="इस महीने की पोस्ट",
       marks=[0,1,2,3,4,6,7,8,9,10,12,13,14,15,16,18,19,20,21,22,24,25,26,27,28],
       foot="26 पोस्ट · एक भी दिन नहीं छूटा"),
  dict(kind="ticks", vo="कैप्शन। हैशटैग। पोस्ट का समय।",
       big="तीनों पहले से तय", items=["कैप्शन", "हैशटैग", "पोस्ट का समय"]),
  dict(kind="counter", vo="छह दिन। सात प्लेटफ़ॉर्म।", to="42", unit="पोस्ट हफ़्ते में",
       ramp=["6", "13", "20", "28", "35"],
       sub="छह दिन × सात जगह · एक सुबह का काम"),
  dict(kind="kinetic", vo="अब असली बात सुनिए।",
       big='अब <span class=hl>असली बात।</span>'),
  dict(kind="kinetic", vo="सबसे मुश्किल काम पोस्ट बनाना नहीं है।",
       big='मुश्किल काम<br>बनाना नहीं है।', size="md"),
  dict(kind="kinetic", vo="रोज़ याद रखना है।",
       big='<span class=hl>रोज़ याद रखना है।</span>', size="md"),
  dict(kind="kinetic", vo="पहले महीने सबको जोश रहता है।",
       big='पहले महीने<br>जोश रहता है।', size="md"),
  dict(kind="kinetic", vo="दूसरे महीने एक दिन छूटता है। फिर तीन। फिर पूरा हफ़्ता।",
       big='फिर एक दिन।<br>फिर तीन।<br><span class=hl>फिर पूरा हफ़्ता।</span>', size="md"),
  dict(kind="kinetic", vo="और तीसरे महीने अकाउंट ठंडा।",
       big='तीसरे महीने<br><span class=hl>अकाउंट ठंडा।</span>', size="md"),
  dict(kind="versus", vo="फ़ायदा रीच नहीं है। फ़ायदा ये है कि नागा नहीं पड़ता।",
       a_label="फ़ायदा ये नहीं", a="रीच",
       b_label="फ़ायदा ये है", b="नागा नहीं पड़ता"),
  dict(kind="kinetic", vo="और ऑर्गैनिक में यही एक चीज़ काम करती है।",
       big='ऑर्गैनिक में<br><span class=hl>यही काम करता है।</span>', size="md"),
  dict(kind="end", vo="यही सिस्टम आपके लिए भी लग सकता है।",
       big='यही सिस्टम <span class=hl>आपके लिए भी।</span>'),
]),
]
