# -*- coding: utf-8 -*-
"""Today's LinkedIn leads: real posts, real dates, matched to a price band.

Every row is somebody who published a request for a developer. `asked` is the
post date and it is the most important field here — a four-month-old "looking
for a developer" post is almost always filled, and pitching it spends the one
impression available for nothing.

`tier` is chosen from what they actually described, not from what we would
prefer to sell. Two rows are marked `skip` because the honest answer is that we
should not pitch them at all, and the reason is on the row.
"""
LEADS = [
 dict(id="LI001", name="Abhhijeet Sharma", first="Abhhijeet", asked="2026-09-03",
      where="Noida, UP", who="BDE at Unacademy — project is for a client",
      email="abhhijeetsharma01@gmail.com", wa="", tier="platform",
      li="https://www.linkedin.com/posts/abhhijeet-sharma-b620481b2_ecommerce-webdevelopment-b2b-activity-7501191314408058880-mIZY",
      need="A fully offline business going online with B2B and B2C together; wants a partner who manages it after launch, not just builds it.",
      hook="The B2B and B2C split is the part that decides the build — dealer pricing and a public catalogue are two different products sharing one warehouse."),
 dict(id="LI002", name="Harsh Pawar", first="Harsh", asked="2026-08-13",
      where="India", who="Running CityHive e-commerce for a liquor business",
      email="", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/harsh-pawar-715989251_freelancedeveloper-webdeveloper-cityhive-activity-7493762825765654528-3Fdp",
      need="CityHive store, ~300 products, cart, checkout, payments, SEO. Budget stated: up to ₹1,00,000.",
      hook="300 SKUs is a data problem before it is a design one — category structure and bulk import decide whether this takes two weeks or two months."),
 dict(id="LI003", name="Anmol Chopra", first="Anmol", asked="2026-06-13",
      where="Greater Delhi", who="Co-Founder, Lyfberry",
      email="anmol.chopra@lyfberry.com", wa="", tier="platform",
      li="https://www.linkedin.com/posts/anmol0809_im-looking-for-a-world-class-website-designer-activity-7471512409677963264-OnUw",
      need="A visually exceptional, highly interactive, AI-integrated site for Lyfberry — wants it at par with the best global sites.",
      hook="\"AI-integrated\" is the word that needs pinning down first — a chat widget and a model that actually does something for the user are different budgets."),
 dict(id="LI004", name="Dr Ritu", first="Dr Ritu", asked="2026-07-28",
      where="Greater Delhi", who="Dermatologist, founder at DERMA E",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/dr-ritu-8b022b376_hiring-hiringnow-webdeveloper-activity-7487821707743985664-hkWd",
      need="Modern, SEO-friendly startup website that converts visitors; asked for stack, portfolio and maintenance options.",
      hook="For a clinic the site's job is narrow: make someone book. Everything else on the page is in service of that one button."),
 dict(id="LI005", name="Tanveer M.", first="Tanveer", asked="2026-08-18",
      where="Gurugram", who="Sourcing for a business he knows",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/tanveer-m-1a070a155_looking-for-a-web-development-partner-activity-7495511545720782849-s9qG",
      need="Professional website or web app. Says India-based companies only.",
      hook="Website or web app is the fork worth settling first — logins, dashboards and payments change the build entirely."),
 dict(id="LI006", name="Abrar Nathani", first="Abrar", asked="2026-09-04",
      where="Surat, Gujarat", who="Owner, Slavi.in — clothing brand",
      email="", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/abrar-nathani-52b1201b8_slavi-modern-womens-fashion-western-activity-7501745022258831361-dLUt",
      need="slavi.in redesign after moving from short kurtis to western and hand-embroidery dresses; wants SEO done properly.",
      hook="A category change is an SEO event, not just a design one — the old kurti URLs carry whatever ranking the store has."),
 dict(id="LI007", name="Ajay Sharma", first="Ajay", asked="2026-08-15",
      where="India", who="SKS Logistics — transport company",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/ajay-sharma-98b04386_looking-for-a-freelance-web-app-developer-activity-7494272777403904001-Bmmw",
      need="Website, corporate email setup, and iOS + Android apps for a transport company.",
      hook="For a transport firm the site and the app answer different people — shippers checking whether you are real, and drivers or customers tracking a load."),
 dict(id="LI008", name="Revanth Kumar Nettem", first="Revanth", asked="2026-08-10",
      where="India", who="ACMA — building a product",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/rknettem_webdevelopment-appdevelopment-mobileappdevelopment-activity-7492446606034690048-sUnp",
      need="Website plus Android and iOS app; explicitly asked for portfolio, stack, timeline and a cost breakup.",
      hook="You asked for a cost breakup, so here is one rather than a capability list."),
 dict(id="LI009", name="Rajeev Baswant", first="Rajeev", asked="2026-08-05",
      where="India", who="Building a real-estate marketplace",
      email="", wa="7738381624", tier="platform",
      li="https://www.linkedin.com/posts/rajeev-baswant-9638a1334_hiring-webdeveloper-appdeveloper-activity-7490905580862234624-cHK5",
      need="A 99acres-style marketplace: web plus Flutter/React Native apps, cloud deployment, RFQ requested.",
      hook="A marketplace lives or dies on the listing and search layer; the apps are the easy half."),
 dict(id="LI010", name="I-Smart Techno Hub", first="", asked="2026-08-11",
      where="Kota / Indore", who="Neetesh Nagar, founder — IT company",
      email="", wa="9251011996", tier="business",
      li="https://www.linkedin.com/posts/i-smart-techno-hub-15803b24b_im-looking-for-an-experienced-website-designer-activity-7493063200675000320-pBx-",
      need="Multi-page premium site for a new business: quote form, SEO, fast loading.",
      hook="He runs an IT company and is outsourcing this — so the work has to survive being reviewed by someone technical."),
 dict(id="LI011", name="Prince Sharma", first="Prince", asked="2026-07-15",
      where="India", who="Chhabili — fashion e-commerce",
      email="", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/prince-sharma-639a18381_i-need-urgent-help-of-software-developer-activity-7483228906817499136-zGn-",
      need="chhabili.com is unfinished — checkout flow, missing pages, general polish.",
      hook="Open the site before writing: the gaps his own commenters listed are checkout, About, privacy and footer."),
 dict(id="LI012", name="Neeraj Kumar E", first="Neeraj", asked="2026-05-05",
      where="India", who="Sourcing a tech partner for a client",
      email="", wa="", tier="platform",
      li="https://www.linkedin.com/posts/neeraj-kumar-e-217412133_looking-for-a-tech-partner-for-a-b2c-app-activity-7457304129330208769-r49V",
      need="Premium seafood and meat D2C: consumer app, website, order and delivery tracking, payments, loyalty.",
      hook="Perishable delivery makes slot booking and live tracking core, not nice-to-have."),
 dict(id="LI013", name="K. Ayush", first="Ayush", asked="2026-03-09",
      where="India", who="Maa Vindhwasini Enterprises — fabrication",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/k-ayush-962b7b177_websitedeveloper-freelancer-webdevelopment-activity-7436695256651264000-Erfu",
      need="Company profile, product showcase, enquiry form, mobile-friendly, basic SEO.",
      hook="For a fabrication unit the site is a catalogue a buyer can forward to his own boss."),
 dict(id="LI016", name="Naveen Sharma — Baisaa Fashion", first="Naveen", asked="2026-09-02",
      where="Delhi", who="Founder, BAISAA FASHION", email="", wa="", tier="platform",
      li="https://www.linkedin.com/posts/naveensharmaofficial_wearehiring-hiring-appdeveloper-activity-7500956585314328576-Q07b",
      need="Fashion e-commerce: website + Android + iOS, payments, orders and tracking, stock sync, admin panel, Play Store and App Store, plus long-term maintenance. Wants monthly engagement, not a build-and-vanish.",
      hook="\"App bana ke chala jaye\" is the failure you named, and it is the right one to fear — the maintenance year costs more than the build and is where most quotes go quiet."),
 dict(id="LI017", name="Naveen Alagendran", first="Naveen", asked="2026-07-07",
      where="India", who="Building a company's first digital identity",
      email="naveenalagendrancompany@gmail.com", wa="", tier="business",
      li="https://www.linkedin.com/posts/naveen-alagendran-3460b297_hiring-webdevelopment-websitedesigner-activity-7480097917572370432-0sMR",
      need="Corporate website plus logo and brand identity; asked explicitly for pricing, timeline, process and portfolio in the reply.",
      hook="You asked for pricing, timeline and process in writing — so this is all three, in that order."),
 dict(id="LI018", name="Nitant Mittal — Nitara Primes", first="Nitant", asked="2026-08-18",
      where="India", who="Building a functional beverage line",
      email="", wa="", tier="business",
      li="https://www.linkedin.com/posts/nitantmittal_nitaraprimes-functionalbeverages-designhiring-activity-7495364977566916608-Vr6I",
      need="Brand identity, packaging and website for a new beverage line, milestone by milestone. Bootstrapped, paying for outcomes rather than retainers.",
      hook="Paying per milestone rather than per month is the right instinct for a bootstrapped launch, and it happens to be how we price anyway."),
 dict(id="LI019", name="Shruti Jain — Vedakosh", first="Shruti", asked="2026-07-10",
      where="Raipur, Chhattisgarh", who="Founder, Vedakosh — personal care",
      email="", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/shruti-jain-7228a0347_currently-looking-for-someone-to-build-a-activity-7481325551589154816-Ehrv",
      need="First website for a personal care D2C brand; asking founders whether WordPress is the right platform.",
      hook="Your thread turned into eight people arguing WordPress versus Shopify, which is the wrong first question — the right one is whether the site's job is selling or explaining, and for personal care it is usually explaining first."),
 dict(id="LI020", name="Avinash Kumar Jha — Ckarfe", first="Avinash", asked="2026-08-02",
      where="Faridabad, Haryana", who="Launching apparel brand Ckarfe",
      email="ckarfe.clothing@gmail.com", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/avinash-kumar-jha-8851b9178_shopifydeveloper-ecommerce-d2c-activity-7489778681523949568-gwaF",
      need="Turn-key Shopify store for ckarfe.com: theme, Razorpay/Cashfree with COD verification, Shiprocket/NimbusPost, mobile-first, SEO, policy pages.",
      hook="COD verification is the line item that decides whether this store is profitable — without OTP confirmation, Indian apparel routinely sees a quarter of COD orders returned undelivered."),
 dict(id="LI021", name="Ritesh Singh — Attire World", first="Ritesh", asked="2026-06-28",
      where="Mumbai", who="Head of Sourcing, ATTIRE WORLD",
      email="", wa="", tier="commerce",
      li="https://www.linkedin.com/posts/ritesh-singh-7b648718_looking-for-a-freelance-website-developer-activity-7476816028170244096-v5n3",
      need="Conversion-focused e-commerce site for a men's ethnic fashion brand: catalogue with categories, filters and search, payment gateway. Asked for quotation.",
      hook="Filters are where ethnic fashion sites lose the sale — size, fabric and occasion, not just category, because that is how the customer actually shops."),
 # ── not pitching, and the reason ──────────────────────────────────────────
 dict(id="LI022", name="Recruiters and agencies (7 found this week)", first="", asked="2026-09-07",
      where="Patna, Kolkata, Delhi", who="", email="", wa="", tier="business", skip=
      "Saurabh Kumar (Taskmitra/Digilabss), Bhaskar Mishra (Intineri Infosol), "
      "Prashant Sharma (Team Sapco), Savan Seth, Zahid Raza, Chintan Shah "
      "(3i Web Experts), Heet Kanabar. Every one is HIRING a developer — salary "
      "₹15,000–30,000 a month in one case — not buying a website. These are "
      "employers and competitors. Most 'urgent hiring web developer' posts in "
      "any given week are this, which is why raw volume is a bad measure.",
      li="https://www.linkedin.com/posts/bhaskar-mishra-714a51226_hiring-webdeveloper-wordpressdeveloper-activity-7502611123867701248-MbRH",
      need="Recruitment posts, not client demand.", hook=""),
 dict(id="LI023", name="Prateek Midha / Vinay Sattu", first="", asked="2026-09-04",
      where="Gurgaon / India", who="", email="", wa="", tier="platform", skip=
      "Both are seeking a technical CO-FOUNDER with equity, and Vinay Sattu "
      "writes it outright: 'I'm not looking to outsource this to an agency.' "
      "Pitching a build to someone who said that reads as not having read it.",
      li="https://www.linkedin.com/posts/prateekmidha_seeking-a-technical-co-foundercto-i-am-activity-7501560950173433856-pwvm",
      need="Technical co-founder, equity, not a paid build.", hook=""),
 dict(id="LI014", name="Shivani Joshi", first="Shivani", asked="2026-09-02",
      where="India", who="", email="", wa="", tier="business", skip=
      "Her post ends 'PS: no agencies.' Pitching as a company is ignoring the "
      "one thing she asked for. Only worth answering as an individual.",
      li="https://www.linkedin.com/posts/shivani1019_im-looking-for-a-freelance-website-developer-activity-7500779245212700673-FECc",
      need="Freelance website developer for an upcoming project.", hook=""),
 dict(id="LI015", name="Daya (darebyte)", first="Daya", asked="2026-07-19",
      where="Aligarh, UP", who="Founder, darebyte", email="", wa="",
      tier="business", skip=
      "Budget ₹12,000 for Apple-style 3D scroll animation. A stranger already "
      "told him in his own comments that it is not possible at that price. "
      "Taking it means losing money or disappointing him.",
      li="https://www.linkedin.com/posts/dayashanknar_hiring-a-website-developer-freelancer-activity-7484559393834074112-zwlo",
      need="Premium LED brand site with 3D product visuals and scroll storytelling.", hook=""),
]
